### ISSUE TITLE
숙련 Parking 개인 과제 피드백

### ISSUE THREAD

**Issue by modolee** [fierceCry/Node.js-Skilled-Parking-Personal-Tasks#17]
# 총평
- 빠르게 제출하기도 했고, 만규님의 백그라운드를 알고 있기 때문에 더욱 높은 기준으로 피드백했다는 것 감안하시고 보시면 좋을 것 같습니다.
- 환경변수 관리나 README 작성 등 신경써서 작성한게 보여서 좋습니다.
- 코드를 깔끔하고 빠르게 구현하는 것은 매우 좋습니다. 하지만! 요구사항과 다르게 구현 된 코드는 아무리 빠르게 만들었다고 하더라도 좋은 코드가 될 수는 없습니다.
- 고생 많으셨고, 요구사항 문서 다시 한번 확인하셔서 내가 놓친 부분이 뭔가 제대로 파악하시기 바랍니다.

# API 명세서
- 이번 캠프 중에서 처음 작성한 것 치고는 깔끔하게 잘 작성했습니다. 다만 디테일한 부분을 만~이 놓치고 있습니다.

## 업데이트 되지 않은 정보
- 회원가입, 로그인의 실제 구현은 /auth가 prefix로 붙도록 되어 있는데, API 명세서에는 /users가 붙어 있습니다.
- 제출한 주소가 https://sprta-products.shop/api 로 되어 있어서 https://sprta-products.shop/api/auth 형태로 되어 있을 줄 알았는데, api들은 또 그냥 /api prefix 없이 사용을 하네요. 뭔가 자꾸 예상을 벗어나게 설계되었다는 생각이 많이 듭니다.

## URL 설계
- URL 설계에 대해서는 제출 전 한번 피드백 드리긴했지만, 아직 완벽하게 이해한 것 같진 않습니다.
- Query Parameters의 사용 방법을 잘 모르고 있는 것을 보입니다. 아래와 같이 작성했는데, 여러 개의 값을 넘길 때에는 맨 처음만 `?`를 붙이고 그 다음에는 `&`로 연결해야 합니다.
```
/users?sort=DESC?status=APPLY? -> X
/users?sort=DESC&status=APPLY -> O
```
- 지금 작성한 API은 마치 중복되는 URL이 하나도 없어야 된다는 생각으로 만든 것 같습니다. 중복되는 URL은 있어도 되며, 다만 용도에 따라서 Method를 다르게 하면 되는 것입니다. CRUD를 기준으로 했을 때 아래를 기본이라고 생각하시면 됩니다.
```
// 이력서 API (앞의 /api 는 넣지 않아도 됩니다.)

이력서 생성 POST /api/resumes
이력서 목록 조회 GET /api/resumes
이력서 상세 조회 GET /api/resumes/:resumeId
이력서 수정 PUT /api/resumes/:resumeId
이력서 삭제 DELETE /api/resumes/:resumeId

// 만약 특정 이력서에 상태 또는 로그에 대한 API를 만들고 싶다면
이력서 로그 목록 조회 GET /api/resumes/:resumeId/logs
이력서 상태 수정 PATCH /api/resumes/:resumeId/status
```

- 참고
  - RESTful 기본: https://restfulapi.net/rest-api-design-tutorial-with-example/
  - 하위 리소스에 대한 설계 방식: https://www.moesif.com/blog/technical/api-design/REST-API-Design-Best-Practices-for-Sub-and-Nested-Resources/

## 요구사항 놓침
- 회원가입 시 Role을 추가한 의도는 알겠지만, 이렇게 될 경우에는 누구나 채용담당자로 회원가입을 할 수 있게 됩니다.

- 로그아웃은 AccessToken이 아니라 RefreshToken으로 인증되어야 합니다.
![image](https://github.com/fierceCry/Node.js-Skilled-Parking-Personal-Tasks/assets/34900418/c34f0dba-4e21-47bb-adb4-338e73c01cd6)

- 이력서 로그 목록 조회는 채용 담당자만 접근할 수 있어야 하는데, API 명세서를 잘못 작성하다 보니 구현도 잘못되었네요. 요구사항은 놓치지 않고 꼼꼼하게 확인하는 것도 중요합니다.
![image](https://github.com/fierceCry/Node.js-Skilled-Parking-Personal-Tasks/assets/34900418/dfa06951-ac4b-4ffd-b286-24193471a5af)

## Response 일관성 부족
- 어떤 API는 data라는 key에 정보를 담아서 주고 다른 API는 곧바로 정보가 나오는 경우도 있습니다. 일관적이지 않는 Response는 사용자(FE 개발자)에게 좋지 않은 UX를 제공합니다.

# ERD & Schema
- ERD에 작성한 Table 이름과 Schema에 작성한 Table 이름이 서로 다릅니다. 그리고 ERD에서 refreshToken은 오타도 있고 이름 규칙도 다른 Table들과는 다르네요. DB에서 이름 규칙은 snake_case를 기준으로 합니다. prisma 스키마 정의 할 때에도 @@map('user')와 같이 해야 되는게 맞겠죠?

- 사용하지 않는 속성을 포함하고 있습니다. resumes.supportReason. 그리고 ERD와 이름도 서로 다르게 정의되어 있습니다.

- role을 enum으로 관리한 것 좋습니다. status도 enum으로 관리했다면 더 좋았을 것 같네요.
- 여러 개의 RefreshToken이 발급되면 안되기에 user : refresh_token = 1:1 관계가 되어야 합니다.

- 잘못 된 의미의 단어를 사용하면 오히려 혼란을 줄 수 있습니다. 여기서의 지원은 support가 아니라 apply를 의미합니다.

# 유효성 검증
- 미들웨어로 따로 빼서 가독성을 높였습니다.
- Joi의 다양한 기능을 잘 활용하여 꼼꼼하게 유효성 검증을 진행한 점 좋습니다.

# 인증

- 인증에서 사용하는 각종 비밀 정보들을 환경변수로 관리한 점 좋습니다.
- 자주 사용하는 메세지들을 상수로 관리한 점도 좋습니다.

## 객체 구조 분해 할당
- 아래 코드를 객체 구조 분해 할당을 이용했다면, 더 간단하게 코드를 작성할 수 있었을 것 같네요.
```javascript
const { email, password, nickName, role } = req.body;

// 생략

const { password: _, ...data } = await prisma.user.create({
  data: {
    email,
    password: hashPassword,
    nickname: nickName, // body로 받는 이름과 DB에 저장하는 이름이 달라서 불필요한 코드 변환이 발생
    role,
  },
});
res.status(201).json({ data });
```
https://github.com/fierceCry/Node.js-Skilled-Parking-Personal-Tasks/blob/03eea89f590dca12b320d3caff20d3dd0efe0ee5/src/routers/auth.router.js#L15-L20

## RefreshToken
- RefreshToken을 DB에 저장해서 관리하는 이유는 토큰이 유출되었을 때 유출 된 토큰으로 접근을 막히 위함입니다. 그런데 중복해서 토큰을 저장할 수 있게 되면 유출 된 경우 폐기되는게 아니라 추가 발행이되는 것입니다. 물론 지금 refreshTokenMiddleware의 구현 자체가 가장 마지막에 만든 값과 비교하고 있어서 유출 된 토큰으로 접근이 불가능 할 것이지만, 그렇다고 하더라도 조금 더 견고하게 만들 필요는 있습니다.
- create가 아니라 upsert와 같이 없으면 생성하고 있으면 갱싱하는 형태가 되어야 합니다.
- RefreshToken 저장 시 Hash 하지 않고 그냥 저장하고 있습니다.

# CRUD
## 항상 내 이력서 조회가 안되는 버그
- user_id라는 속성이 없기 때문에 아래 조건이 항상 참이 되어 내 이력서 조회가 불가능합니다.
https://github.com/fierceCry/Node.js-Skilled-Parking-Personal-Tasks/blob/03eea89f590dca12b320d3caff20d3dd0efe0ee5/src/routers/resumes.router.js#L74-L76

## Response 형태
- 사용자 입장에서 아래 두 가지 데이터 형태 중 어떤 것이 사용하지 좋을까요?
```json
{
  "id": 4,
  "user": {
    "nickname": "채용담당자"
  },
  "title": "튼튼한 개발자 스파르탄 200",
  "content": "200 저는 튼튼함을 제 자랑거리로 선보일 수 있습니다. 어떤 도전이든 두려워하지 않고, 견고한 코드와 해결책을 제시할 자신이 있습니다. 복잡한 문제에 직면했을 때에도 냉정하게 분석하고 빠르게 대응하는 능력을 갖췄습니다. 또한, 팀원들과의 원활한 커뮤니케이션을 통해 프로젝트의 성공을 이끌어내는데 기여할 것입니다. 최고의 결과물을 위해 끊임없",
  "supportStatus": "APPLY",
  "createdAt": "2024-05-28T00:37:08.086Z",
  "updatedAt": "2024-05-28T00:37:08.086Z"
},
{
  "id": 4,
  "nickname": "채용담당자",
  "title": "튼튼한 개발자 스파르탄 200",
  "content": "200 저는 튼튼함을 제 자랑거리로 선보일 수 있습니다. 어떤 도전이든 두려워하지 않고, 견고한 코드와 해결책을 제시할 자신이 있습니다. 복잡한 문제에 직면했을 때에도 냉정하게 분석하고 빠르게 대응하는 능력을 갖췄습니다. 또한, 팀원들과의 원활한 커뮤니케이션을 통해 프로젝트의 성공을 이끌어내는데 기여할 것입니다. 최고의 결과물을 위해 끊임없",
  "supportStatus": "APPLY",
  "createdAt": "2024-05-28T00:37:08.086Z",
  "updatedAt": "2024-05-28T00:37:08.086Z"
}
```

## 수정 시 있는 데이터만 사용
- 해설 영상에 나온 내용 잘 활용하셨네요!
https://github.com/fierceCry/Node.js-Skilled-Parking-Personal-Tasks/blob/03eea89f590dca12b320d3caff20d3dd0efe0ee5/src/routers/resumes.router.js#L115-L118

# Transaction
- prisma라는 이름으로 사용할 경우 혼선의 여지가 있으니, 명확하게 transaction이라는 것을 알 수 있도록 tx와 같은 이름을 사용하는게 좋습니다.
https://github.com/fierceCry/Node.js-Skilled-Parking-Personal-Tasks/blob/03eea89f590dca12b320d3caff20d3dd0efe0ee5/src/routers/resumes.router.js#L169

**Comment by fierceCry** [comment]
# API 변경 사항 요약

## 1. 경로 변경
- 회원가입 및 로그인 URL을 `/users`에서 `/auth`로 변경하였습니다.

## 2. URL 설계
- Query Parameters 사용에 대한 경험이 부족하여 현재 URL은 수정하였습니다.

## 3. 회원가입 요구사항 수정
- 회원가입 시 `Role`을 추가로 넣는 요구사항을 제거하여, 누구나 채용담당자로 회원가입하지 못하도록 수정하였습니다.

## 4. 로그아웃 인증 방식 변경
- 로그아웃 시 `AccessToken`으로 인증하는 것에서 `RefreshToken`으로 인증하는 것으로 변경하였습니다.

## 5. 이력서 로그 목록 조회 변경
- 채용담당자만 이력서를 조회할 수 있도록 역할 인가를 추가하였습니다.

## 6. 응답 데이터 일관성 개선
- 응답 데이터의 일관성 부족 문제를 해결하기 위해 `data`라는 key에 정보를 담아 전달하도록 수정하였습니다.
- `nickname`을 `user`에 담아서 보내는 것에서 `map` 함수를 사용하여 `nickname`만 꺼내어 보내도록 수정하였습니다.

## 7. 스키마 변경
- Schema를 `@@map('user')`와 같이 snake_case 기준으로 수정하였습니다.
- `role`을 `enum`으로 관리하였습니다.
- `user` 테이블과 `refresh_token` 테이블을 1:1 관계로 수정하였습니다.

## 8. RefreshToken 처리 변경
- 클라이언트에게 `RefreshToken`을 Hash하지 않고 보내고, 저장할 때는 Hash하여 저장하도록 수정하였습니다.

## 9. Transaction 명명 변경
- Transaction 사용 시 `prisma`의 이름을 `tx`로 수정하였습니다.
